name: CI/CD

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: false

env:
  ENV_FILE: .ci-cd.env

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Just say echo to see if it work
        run: echo it worked
        shell: bash
